#!/usr/bin/env python3
"""
One-off import: reads the 'ALL' sheet of a Client Lists.xlsx file and emits
a single SQL DO block to stdout that inserts the rows as patients.

Usage:
    python scripts/import_patients_from_xlsx.py /path/to/Client\\ Lists.xlsx \\
        > supabase/import/01_patients_from_all_sheet.sql

Then paste the generated SQL into Supabase SQL Editor and run it once.

Requires: openpyxl (`pip install openpyxl` in a venv).
"""
from __future__ import annotations

import re
import sys
from openpyxl import load_workbook

ALL_SHEET = "ALL"


def normalize_phone(v) -> str | None:
    if v is None:
        return None
    s = str(v).strip()
    # Excel stores numeric phones as floats: '9952011968.0' -> drop the '.0' artifact
    # before stripping non-digits, otherwise we'd lose the leading digit.
    if s.endswith(".0"):
        s = s[:-2]
    digits = re.sub(r"\D", "", s)
    if len(digits) < 10:
        return None
    return digits[-10:]


def clean_text(v) -> str | None:
    if v is None:
        return None
    s = str(v).strip()
    if not s or s.lower() in {"nan", "none", "-", "--", "---", "..."}:
        return None
    if set(s) <= {"-", " "}:
        return None
    return s


def format_client_number(v) -> str | None:
    if v is None:
        return None
    s = str(v).strip()
    if not s or s in {"*", "-", "nan"}:
        return None
    try:
        return str(int(float(s)))
    except (ValueError, TypeError):
        return s


def build_notes(concern, remarks) -> str | None:
    parts = []
    c = clean_text(concern)
    if c:
        parts.append(f"Initial concern: {c}")
    r = clean_text(remarks)
    if r:
        parts.append(f"Remarks: {r}")
    return " | ".join(parts) if parts else None


def format_legacy_client_no_int(client_no) -> int | None:
    if client_no is None:
        return None
    s = str(client_no).strip()
    if not s or s in {"*", "-", "nan"}:
        return None
    try:
        return int(float(s))
    except (ValueError, TypeError):
        return None


def sql_str(s: str | None) -> str:
    if s is None:
        return "NULL"
    return "'" + s.replace("'", "''") + "'"


def main(path: str) -> int:
    wb = load_workbook(path, data_only=True, read_only=True)
    if ALL_SHEET not in wb.sheetnames:
        print(f"ERROR: sheet {ALL_SHEET!r} not found in {path}", file=sys.stderr)
        return 1
    ws = wb[ALL_SHEET]
    rows = list(ws.iter_rows(values_only=True))

    # Header is row 2 (1-indexed). Data starts at row 3.
    data = rows[2:]

    # Column indices observed in the ALL sheet:
    #   1: CLIENT NUMBER     3: NAME       4: Concern     6: CONTACT NUMBER     9: REMARKS

    records: list[tuple[str, str, int | None, str | None]] = []
    seen_phones: set[str] = set()
    seen_legacy_nos: set[int] = set()
    skipped_no_name = 0
    skipped_no_phone = 0
    skipped_dup_phone = 0
    dedup_legacy_nos = 0

    for r in data:
        if r is None or len(r) < 7:
            continue
        client_no = r[1]
        name = clean_text(r[3]) if len(r) > 3 else None
        concern = r[4] if len(r) > 4 else None
        phone_raw = r[6] if len(r) > 6 else None
        remarks = r[9] if len(r) > 9 else None

        if not name:
            skipped_no_name += 1
            continue

        phone = normalize_phone(phone_raw)
        if not phone:
            skipped_no_phone += 1
            continue

        if phone in seen_phones:
            skipped_dup_phone += 1
            continue
        seen_phones.add(phone)

        legacy_no = format_legacy_client_no_int(client_no)
        # The legacy_client_no column has a unique-per-clinic constraint; if
        # we'd hit a duplicate, drop the number and keep the row.
        if legacy_no is not None and legacy_no in seen_legacy_nos:
            legacy_no = None
            dedup_legacy_nos += 1
        elif legacy_no is not None:
            seen_legacy_nos.add(legacy_no)

        notes = build_notes(concern, remarks)
        records.append((name, phone, legacy_no, notes))

    summary = (
        f"-- {len(records)} patient rows; skipped: "
        f"{skipped_no_name} no-name, {skipped_no_phone} no-phone, "
        f"{skipped_dup_phone} dup phones; "
        f"dropped legacy_client_no on {dedup_legacy_nos} dup numbers."
    )
    print(f"-- Generated from: {path}", file=sys.stderr)
    print(summary, file=sys.stderr)

    # ---- Emit SQL ----
    out = []
    out.append("-- One-off import of patients from Client Lists.xlsx → ALL sheet.")
    out.append("-- Generated by scripts/import_patients_from_xlsx.py")
    out.append(f"-- Source: {path}")
    out.append(summary)
    out.append("-- Requires migration 0007_patients_legacy_client_no.sql to be applied first.")
    out.append("-- Apply once via Supabase SQL Editor.")
    out.append("")
    out.append("-- ============================================================")
    out.append("-- STEP 0: Wipe all existing patient & visit rows before real import.")
    out.append("-- Visits go first because patients.id is FK-referenced by visits.patient_id")
    out.append("-- with ON DELETE RESTRICT.")
    out.append("-- This is a hard reset. Do not re-run after the real data is in.")
    out.append("-- ============================================================")
    out.append("delete from visits;")
    out.append("delete from patients;")
    out.append("")
    out.append("-- ============================================================")
    out.append("-- STEP 1: Import real patient rows")
    out.append("-- ============================================================")
    out.append("do $$")
    out.append("declare")
    out.append("  v_clinic uuid;")
    out.append("  v_before int;")
    out.append("  v_after int;")
    out.append("begin")
    out.append("  select id into v_clinic from clinics limit 1;")
    out.append("  if v_clinic is null then")
    out.append("    raise exception 'No clinic row. Apply 0005_seed_dev.sql first.';")
    out.append("  end if;")
    out.append("  select count(*) into v_before from patients;")
    out.append("")
    out.append("  insert into patients (clinic_id, name, phone, legacy_client_no, notes) values")

    lines = []
    for name, phone, legacy_no, notes in records:
        legacy_sql = "NULL" if legacy_no is None else str(legacy_no)
        lines.append(
            f"    (v_clinic, {sql_str(name)}, {sql_str(phone)}, {legacy_sql}, {sql_str(notes)})"
        )
    out.append(",\n".join(lines))
    out.append("  ;")
    out.append("")
    out.append("  select count(*) into v_after from patients;")
    out.append("  raise notice 'Imported % patient rows (% -> %).', v_after - v_before, v_before, v_after;")
    out.append("end$$;")
    out.append("")

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        sys.exit(2)
    sys.exit(main(sys.argv[1]))
